on: [push, pull_request]
name: pREST CI

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:alpine
        env:
          POSTGRES_USER: ""
          POSTGRES_DB: prest-test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - name: Setup Database
        env:
          PREST_PG_HOST: localhost
          PREST_PG_PORT: 5432
          PREST_PG_USER: postgres
          PREST_PG_DATABASE: prest-test
        run: psql -d $PREST_PG_DATABASE -h $PREST_PG_HOST -p $PREST_PG_PORT -U $PREST_PG_USER -f ./testdata/schema.sql

      - name: Set up Go 1.15
        uses: actions/setup-go@v1
        with:
          go-version: 1.15

      - name: Install Dependencies
        run: |
          echo "Installing DeepSource"
          sudo sed -i 's/azure\.//' /etc/apt/sources.list
          sudo apt-get update
          curl https://deepsource.io/cli | sh
          echo "Installing GolangCI Lint"
          curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sudo bash -s -- -b $GOPATH/bin v1.15.0
          sudo apt -y install gcc-multilib postgresql-contrib
          git config --global --add url."git@github.com:prest".insteadOf "https://github.com/prest"
          go get -v -d ./...
          go get -v github.com/inconshreveable/mousetrap
          go get golang.org/x/tools/cmd/cover
          go get github.com/mattn/goveralls

      - name: Install golang-migrate
        run: |
          curl -L https://github.com/golang-migrate/migrate/releases/download/v4.12.2/migrate.linux-amd64.tar.gz | tar xvz
          sudo mv migrate.linux-amd64 /usr/bin/migrate
          which migrate

      - name: Test
        run: |
          curl -sfL https://git.io/goreleaser | sh -s -- check
          sh testdata/migrations_test.sh
          env go test -race -covermode=atomic -coverprofile=coverage.out ./...
